modules/web-base/src/main/java/org/nlh4j/web/system/user/dto/UserDto.java
/*
 * @(#)UserDto.java 1.0 Aug 28, 2015
 * Copyright 2015 by GNU Lesser General Public License (LGPL). All rights reserved.
 */
package org.nlh4j.web.system.user.dto;

import java.util.Locale;

import org.seasar.doma.Entity;
import org.seasar.doma.jdbc.entity.NamingType;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import org.nlh4j.util.LocaleUtils;
import org.nlh4j.web.base.util.SessionUtils;
import org.nlh4j.web.core.domain.entity.RoleGroup;

/**
 * An extended class of {@link org.nlh4j.web.core.dto.UserDto}
 *
 * @author Hai Nguyen (hainguyenjc@gmail.com)
 *
 */
@EqualsAndHashCode(callSuper = false)
@Entity(naming = NamingType.SNAKE_UPPER_CASE)
public class UserDto extends org.nlh4j.web.core.domain.entity.UserEx {

    /** */
    private static final long serialVersionUID = 1L;
    /** {@link RoleGroup} name */
    @Getter
    @Setter
    private String groupName;
    /** Specify whether changing password */
    @Getter
    @Setter
    private boolean changepwd = false;

    /* (Non-Javadoc)
     * @see org.nlh4j.core.dto.UserDetails#getLocale()
     */
    @JsonIgnore
    public Locale getLocale() {
        Locale locale = null;
        try { locale = LocaleUtils.toLocale(super.getLanguage()); }
        catch(Exception e) { locale = null; }
        return locale;
    }
    public String getDisplayLanguage() {
        Locale locale = this.getLocale();
        return (locale == null ? "" : locale.getDisplayLanguage());
    }

    /**
     * Get a boolean value indicating that this information whether is current logged-in user
     *
     * @return true for current user; else false
     */
    public boolean isCurrentUser() {
        return SessionUtils.getUid().equals(super.getId());
    }
}

modules/web-base/src/main/java/META-INF/resources/WEB-INF/views/S0200/listColumns.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/tags/Common.inc" %>

<%-- START: System Administrator --%>
<c:if test="${nlh4jBase:isSystemAdmin()}">
<c:if test="${company == null}">
<th type="no" width="5%">#</th>
<th width="10%"><spring:message code="${pageModule}.columns.user.name" /></th>
<th width="10%"><spring:message code="${pageModule}.columns.company.code" /></th>
<th width="15%"><spring:message code="${pageModule}.columns.company.name" /></th>
<th width="10%"><spring:message code="${pageModule}.columns.group.code" /></th>
<th width="15%"><spring:message code="${pageModule}.columns.group.name" /></th>
<th width="10%"><spring:message code="${pageModule}.columns.user.email" /></th>
<th width="5%" type="enum"><spring:message code="${pageModule}.columns.user.language" /></th>
<th width="5%" type="enum"><spring:message code="${pageModule}.columns.user.enabled" /></th>
<th width="5%" type="enum"><spring:message code="${pageModule}.columns.user.sysadmin" /></th>
<th width="10%" type="date"><spring:message code="${pageModule}.columns.user.expired.at" /></th>
</c:if>
<c:if test="${company != null}">
<th type="no" width="5%">#</th>
<th width="10%"><spring:message code="${pageModule}.columns.user.name" /></th>
<th width="10%"><spring:message code="${pageModule}.columns.group.code" /></th>
<th width="20%"><spring:message code="${pageModule}.columns.group.name" /></th>
<th width="25%"><spring:message code="${pageModule}.columns.user.email" /></th>
<th width="10%" type="enum"><spring:message code="${pageModule}.columns.user.language" /></th>
<th width="5%" type="enum"><spring:message code="${pageModule}.columns.user.enabled" /></th>
<th width="5%" type="enum"><spring:message code="${pageModule}.columns.user.sysadmin" /></th>
<th width="10%" type="date"><spring:message code="${pageModule}.columns.user.expired.at" /></th>
</c:if>
</c:if>
<%-- END: System Administrator --%>
<%-- START: Normal User --%>
<c:if test="${!nlh4jBase:isSystemAdmin()}">
<th type="no" width="5%">#</th>
<th width="15%"><spring:message code="${pageModule}.columns.user.name" /></th>
<th width="10%"><spring:message code="${pageModule}.columns.group.code" /></th>
<th width="20%"><spring:message code="${pageModule}.columns.group.name" /></th>
<th width="25%"><spring:message code="${pageModule}.columns.user.email" /></th>
<th width="10%" type="enum"><spring:message code="${pageModule}.columns.user.language" /></th>
<th width="5%" type="enum"><spring:message code="${pageModule}.columns.user.enabled" /></th>
<th width="10%" type="date"><spring:message code="${pageModule}.columns.user.expired.at" /></th>
</c:if>
<%-- END: Normal User --%>

modules/web-base/src/main/java/META-INF/resources/WEB-INF/views/S0200/listItems.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/tags/Common.inc" %>

<%-- START: System Administrator --%>
<c:if test="${nlh4jBase:isSystemAdmin()}">
<c:if test="${company == null}">
<td type="no">{{$index + 1}}</td>
<td>{{data.username}}</td>
<td>{{data.companyCode}}</td>
<td>{{data.companyName}}</td>
<td>{{data.groupCode}}</td>
<td>{{data.groupName}}</td>
<td>{{data.email}}</td>
<td type="enum">{{data.displayLanguage}}</td>
<td type="enum">
	<input type="checkbox" name="checkbox" ng-model="data.enabled" disabled="disabled">
</td>
<td type="enum">
	<input type="checkbox" name="checkbox" ng-model="data.sysadmin" disabled="disabled">
</td>
<td width="10%" type="date">{{data.expiredAt | date:'${cmnDateTimePattern}'}}</td>
</c:if>
<c:if test="${company != null}">
<td type="no">{{$index + 1}}</td>
<td>{{data.username}}</td>
<td>{{data.groupCode}}</td>
<td>{{data.groupName}}</td>
<td>{{data.email}}</td>
<td type="enum">{{data.displayLanguage}}</td>
<td type="enum">
	<input type="checkbox" name="checkbox" ng-model="data.enabled" disabled="disabled">
</td>
<td type="enum">
	<input type="checkbox" name="checkbox" ng-model="data.sysadmin" disabled="disabled">
</td>
<td width="10%" type="date">{{data.expiredAt | date:'${cmnDateTimePattern}'}}</td>
</c:if>
</c:if>
<%-- END: System Administrator --%>
<%-- START: Normal User --%>
<c:if test="${!nlh4jBase:isSystemAdmin()}">
<td type="no">{{$index + 1}}</td>
<td>{{data.username}}</td>
<td>{{data.groupCode}}</td>
<td>{{data.groupName}}</td>
<td>{{data.email}}</td>
<td type="enum">{{data.displayLanguage}}</td>
<td type="enum">
	<input type="checkbox" name="checkbox" ng-model="data.enabled" disabled="disabled">
</td>
<td width="10%" type="date">{{data.expiredAt | date:'${cmnDateTimePattern}'}}</td>
</c:if>
<%-- END: Normal User --%>

modules/web-base/src/main/java/META-INF/resources/WEB-INF/views/S0200/searchForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/tags/Common.inc" %>

<!-- START: user name -->
<div class="input-group col-md-3" style="float: left;">
	<span class="input-group-addon" id="basic-addon1">
		<i class="fa fa-user fa-2"></i></span>
	<input type="text" class="form-control"
	placeholder="<spring:message code="${pageModule}.search.username.prompt" />"
	aria-describedby="basic-addon1"
	ng-model="model.search.keyword">
</div>
<!-- END: user name -->
<!-- START: status -->
<div class="input-label-control-group">
	<label class="control-label">
		<spring:message code="${pageModule}.search.status.enabled" />
	</label>
	<select class="form-control"
	data-ng-model="model.search.enabled">
		<option value=""><spring:message code="${pageModule}.search.status.enabled.prompt" /></option>
		<option value="true"><spring:message code="${pageModule}.search.status.enabled.valid" /></option>
		<option value="false"><spring:message code="${pageModule}.search.status.enabled.invalid" /></option>
	</select>
</div>
<!-- END: status -->
<!-- START: expired -->
<div class="input-label-control-group">
	<label class="control-label">
		<spring:message code="${pageModule}.search.status.expired" />
	</label>
	<select class="form-control"
	data-ng-model="model.search.expired">
		<option value=""><spring:message code="${pageModule}.search.status.expired.prompt" /></option>
		<option value="true"><spring:message code="${pageModule}.search.status.expired.valid" /></option>
		<option value="false"><spring:message code="${pageModule}.search.status.expired.invalid" /></option>
	</select>
</div>
<!-- END: expired -->